create table User(User_Id int primary key AUTO_INCREMENT, Username varchar(20) NOT NULL, Email varchar(20) not null, Password varchar(20) not null, token varchar(255) ,Role varchar(10));

create table Package(Package_id int primary key AUTO_INCREMENT, PackageName varchar(100) NOT NULL, Days int, LocationName varchar(50), ImageLink text, Rating int, Price bigint, Difficulty varchar(50),Transportation varchar(50), Accomodation varchar(50), About text, Itinerary text);

create table Bookings(BookingsId int primary key AUTO_INCREMENT, User_Id int, BookedDate DATE DEFAULT (CURRENT_DATE), Package_id int, status varchar(100) DEFAULT "pending" ,FOREIGN KEY (User_Id) REFERENCES User(User_Id),FOREIGN KEY (Package_id) REFERENCES Package(Package_id) ON DELETE CASCADE);

create table Feedback(FeedbackId int primary key AUTO_INCREMENT, User_Id int, Feed text, status varchar(100) DEFAULT "pending" ,FOREIGN KEY (User_Id) REFERENCES User(User_Id));

create table Rating(RatingId int primary key AUTO_INCREMENT, User_Id int, Ratings int, FOREIGN KEY (User_Id) REFERENCES User(User_Id));

create table Hotel(HotelId int primary key AUTO_INCREMENT, HotelName varchar(100), HotelLocation varchar(100), HotelImage text, HotelPrice bigint, HotelDescription text);

create table CustomPackage(Package_id int primary key AUTO_INCREMENT, User_Id int, TripFrom varchar(100), TripTo varchar(100), DateFrom varchar(100), DateTo varchar(100), Email varchar(100), Children int, Adult int, Phone bigint,BookedDate DATE DEFAULT (CURRENT_DATE), FOREIGN KEY (User_Id) REFERENCES User(User_Id));

INSERT INTO Hotel(HotelName, HotelLocation, HotelImage, HotelPrice, HotelDescription) VALUES("Hotel Adam", "Kathmandu", "https://plus.unsplash.com/premium_photo-1677626376813-1ea652d15288?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80", 100000,"Luxuriate in our elegantly decorated rooms, featuring city skyline views, flat-screen TVs, high-speed internet, and plush bedding. Our on-site restaurant and bar offer gourmet dishes and stunning cocktails while the spa and fitness center provide relaxation and rejuvenation. Our location in the city center makes us the perfect choice for business and leisure travelers.");
INSERT INTO Hotel(HotelName, HotelLocation, HotelImage, HotelPrice, HotelDescription) VALUES("Hotel Lakeside", "Pokhara", "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aG90ZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60", 150000,"Luxuriate in our elegantly decorated rooms, featuring city skyline views, flat-screen TVs, high-speed internet, and plush bedding. Our on-site restaurant and bar offer gourmet dishes and stunning cocktails while the spa and fitness center provide relaxation and rejuvenation. Our location in the city center makes us the perfect choice for business and leisure travelers.");
INSERT INTO Hotel(HotelName, HotelLocation, HotelImage, HotelPrice, HotelDescription) VALUES("Hotel Pokhara", "Kaski", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60", 80000,"Luxuriate in our elegantly decorated rooms, featuring city skyline views, flat-screen TVs, high-speed internet, and plush bedding. Our on-site restaurant and bar offer gourmet dishes and stunning cocktails while the spa and fitness center provide relaxation and rejuvenation. Our location in the city center makes us the perfect choice for business and leisure travelers.");
INSERT INTO Hotel(HotelName, HotelLocation, HotelImage, HotelPrice, HotelDescription) VALUES("Hotel Best", "Jhapa", "https://images.unsplash.com/photo-1596436889106-be35e843f974?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGhvdGVsc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60", 90000,"Luxuriate in our elegantly decorated rooms, featuring city skyline views, flat-screen TVs, high-speed internet, and plush bedding. Our on-site restaurant and bar offer gourmet dishes and stunning cocktails while the spa and fitness center provide relaxation and rejuvenation. Our location in the city center makes us the perfect choice for business and leisure travelers.");
INSERT INTO Hotel(HotelName, HotelLocation, HotelImage, HotelPrice, HotelDescription) VALUES("Hotel Hayat", "Kathmandu", "https://images.unsplash.com/photo-1606046604972-77cc76aee944?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8aG90ZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60", 890000,"Luxuriate in our elegantly decorated rooms, featuring city skyline views, flat-screen TVs, high-speed internet, and plush bedding. Our on-site restaurant and bar offer gourmet dishes and stunning cocktails while the spa and fitness center provide relaxation and rejuvenation. Our location in the city center makes us the perfect choice for business and leisure travelers.");
